import { defineConfig } from "vite"
import react from "@vitejs/plugin-react-swc"
import typescript from "@rollup/plugin-typescript"

const path = require("path")

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({
      jsxImportSource: "@emotion/react",
    }),
  ],
  build: {
    sourcemap: true,
    minify: "esbuild",
    lib: {
      entry: path.resolve(__dirname, "src/index.ts"),
      name: "@zweb-design/react",
      fileName: (format) => `${format}/index.js`,
    },
    rollupOptions: {
      plugins: [
        typescript({
          tsconfig: path.resolve(__dirname, "tsconfig.json"),
          compilerOptions: {
            rootDir: path.resolve(__dirname, "src"),
            outDir: path.resolve(__dirname, "dist", "types"),
            declaration: true,
          },
          include: path.resolve(__dirname, "src/**"),
          exclude: path.resolve(__dirname, "node_modules/**"),
        }),
      ],
      external: [
        "react",
        "react-dom",
        "@emotion/react",
        "framer-motion",
        "@zweb-design/system",
        "@zweb-design/theme",
        "@zweb-design/config-provider",
        "@zweb-design/avatar",
        "@zweb-design/breadcrumb",
        "@zweb-design/icon",
        "@zweb-design/image",
        "@zweb-design/tag",
        "@zweb-design/divider",
        "@zweb-design/space",
        "@zweb-design/button",
        "@zweb-design/radio",
        "@zweb-design/typography",
        "@zweb-design/trigger",
        "@zweb-design/popover",
        "@zweb-design/checkbox",
        "@zweb-design/list",
        "@zweb-design/link",
        "@zweb-design/progress",
        "@zweb-design/empty",
        "@zweb-design/badge",
        "@zweb-design/statistic",
        "@zweb-design/input",
        "@zweb-design/switch",
        "@zweb-design/alert",
        "@zweb-design/input-tag",
        "@zweb-design/grid",
        "@zweb-design/popconfirm",
        "@zweb-design/pagination",
        "@zweb-design/spin",
        "@zweb-design/notification",
        "@zweb-design/input-number",
        "@zweb-design/message",
        "@zweb-design/select",
        "@zweb-design/comment",
        "@zweb-design/description",
        "@zweb-design/timeline",
        "@zweb-design/card",
        "@zweb-design/rate",
        "@zweb-design/calendar",
        "@zweb-design/time-picker",
        "@zweb-design/modal",
        "@zweb-design/steps",
        "@zweb-design/back-top",
        "@zweb-design/drawer",
        "@zweb-design/collapse",
        "@zweb-design/table",
        "@zweb-design/date-picker",
        "@zweb-design/result",
        "@zweb-design/page-header",
        "@zweb-design/slider",
        "@zweb-design/menu",
        "@zweb-design/loading",
        "@zweb-design/tabs",
        "@zweb-design/skeleton",
        "@zweb-design/dropdown",
        "@zweb-design/affix",
        "@zweb-design/cascader",
        "@zweb-design/upload",
      ],
      output: {
        globals: {
          react: "React",
          "react-dom": "ReactDom",
          "@emotion/react": "@emotion/react",
          "framer-motion": "framer-motion",
          "@zweb-design/system": "@zweb-design/system",
          "@zweb-design/theme": "@zweb-design/theme",
          "@zweb-design/config-provider": "@zweb-design/config-provider",
          "@zweb-design/avatar": "@zweb-design/avatar",
          "@zweb-design/breadcrumb": "@zweb-design/breadcrumb",
          "@zweb-design/icon": "@zweb-design/icon",
          "@zweb-design/image": "@zweb-design/image",
          "@zweb-design/tag": "@zweb-design/tag",
          "@zweb-design/divider": "@zweb-design/divider",
          "@zweb-design/space": "@zweb-design/space",
          "@zweb-design/button": "@zweb-design/button",
          "@zweb-design/radio": "@zweb-design/radio",
          "@zweb-design/typography": "@zweb-design/typography",
          "@zweb-design/trigger": "@zweb-design/trigger",
          "@zweb-design/popover": "@zweb-design/popover",
          "@zweb-design/checkbox": "@zweb-design/checkbox",
          "@zweb-design/list": "@zweb-design/list",
          "@zweb-design/link": "@zweb-design/link",
          "@zweb-design/progress": "@zweb-design/progress",
          "@zweb-design/empty": "@zweb-design/empty",
          "@zweb-design/badge": "@zweb-design/badge",
          "@zweb-design/statistic": "@zweb-design/statistic",
          "@zweb-design/input": "@zweb-design/input",
          "@zweb-design/switch": "@zweb-design/switch",
          "@zweb-design/alert": "@zweb-design/alert",
          "@zweb-design/input-tag": "@zweb-design/input-tag",
          "@zweb-design/grid": "@zweb-design/grid",
          "@zweb-design/popconfirm": "@zweb-design/popconfirm",
          "@zweb-design/pagination": "@zweb-design/pagination",
          "@zweb-design/spin": "@zweb-design/spin",
          "@zweb-design/notification": "@zweb-design/notification",
          "@zweb-design/input-number": "@zweb-design/input-number",
          "@zweb-design/message": "@zweb-design/message",
          "@zweb-design/select": "@zweb-design/select",
          "@zweb-design/comment": "@zweb-design/comment",
          "@zweb-design/description": "@zweb-design/description",
          "@zweb-design/timeline": "@zweb-design/timeline",
          "@zweb-design/card": "@zweb-design/card",
          "@zweb-design/rate": "@zweb-design/rate",
          "@zweb-design/calendar": "@zweb-design/calendar",
          "@zweb-design/time-picker": "@zweb-design/time-picker",
          "@zweb-design/modal": "@zweb-design/modal",
          "@zweb-design/steps": "@zweb-design/steps",
          "@zweb-design/back-top": "@zweb-design/back-top",
          "@zweb-design/drawer": "@zweb-design/drawer",
          "@zweb-design/collapse": "@zweb-design/collapse",
          "@zweb-design/table": "@zweb-design/table",
          "@zweb-design/date-picker": "@zweb-design/date-picker",
          "@zweb-design/result": "@zweb-design/result",
          "@zweb-design/page-header": "@zweb-design/page-header",
          "@zweb-design/slider": "@zweb-design/slider",
          "@zweb-design/menu": "@zweb-design/menu",
          "@zweb-design/loading": "@zweb-design/loading",
          "@zweb-design/tabs": "@zweb-design/tabs",
          "@zweb-design/skeleton": "@zweb-design/skeleton",
          "@zweb-design/dropdown": "@zweb-design/dropdown",
          "@zweb-design/affix": "@zweb-design/affix",
          "@zweb-design/cascader": "@zweb-design/cascader",
          "@zweb-design/upload": "@zweb-design/upload",
        },
      },
    },
  },
})
